apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: databeez-ui
  namespace: databeez
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: ui.databeez.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: databeez-ui
                port:
                  number: 80
